https://github.com/docker-library/docs/blob/master/postgres/README.md

https://www.youtube.com/watch?v=QePBbG5MoKk&list=PL4cUxeGkcC9hxjeEtdHFNYMtCpjNBm3h7&index=13
FROM node:17-alpine

WORKDIR /app

COPY 